# Generated by Django 6.0.7 on 2026-08-02 13:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, verbose_name='naziv')),
                ('tip', models.CharField(choices=[('TROSAK', 'Trošak'), ('PRIHOD', 'Prihod')], default='TROSAK', max_length=10, verbose_name='tip')),
                ('boja', models.CharField(default='#0F6E56', max_length=7, verbose_name='boja')),
                ('ikona', models.CharField(blank=True, max_length=50, verbose_name='ikona')),
                ('vlasnik', models.ForeignKey(blank=True, help_text='Prazno znaci sustavska kategorija dostupna svima.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategorije', to=settings.AUTH_USER_MODEL, verbose_name='vlasnik')),
            ],
            options={
                'verbose_name': 'kategorija',
                'verbose_name_plural': 'kategorije',
                'ordering': ['naziv'],
            },
        ),
        migrations.CreateModel(
            name='Transakcija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('TROSAK', 'Trošak'), ('PRIHOD', 'Prihod')], default='TROSAK', max_length=10, verbose_name='tip')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='iznos')),
                ('datum', models.DateField(verbose_name='datum')),
                ('opis', models.CharField(blank=True, max_length=200, verbose_name='opis')),
                ('datum_unosa', models.DateTimeField(auto_now_add=True, verbose_name='datum unosa')),
                ('kategorija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transakcije', to='core.kategorija', verbose_name='kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transakcije', to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
            ],
            options={
                'verbose_name': 'transakcija',
                'verbose_name_plural': 'transakcije',
                'ordering': ['-datum', '-datum_unosa'],
            },
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trgovina', models.CharField(blank=True, max_length=150, verbose_name='trgovina')),
                ('datum_izdavanja', models.DateField(blank=True, null=True, verbose_name='datum izdavanja')),
                ('slika', models.ImageField(blank=True, null=True, upload_to='racuni/%Y/%m/', verbose_name='slika')),
                ('prepoznati_tekst', models.TextField(blank=True, verbose_name='prepoznati tekst')),
                ('datum_spremanja', models.DateTimeField(auto_now_add=True, verbose_name='datum spremanja')),
                ('transakcija', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='racun', to='core.transakcija', verbose_name='transakcija')),
            ],
            options={
                'verbose_name': 'račun',
                'verbose_name_plural': 'računi',
                'ordering': ['-datum_spremanja'],
            },
        ),
        migrations.CreateModel(
            name='Budzet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.PositiveSmallIntegerField(verbose_name='godina')),
                ('mjesec', models.PositiveSmallIntegerField(verbose_name='mjesec')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='iznos')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budzeti', to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
            ],
            options={
                'verbose_name': 'budžet',
                'verbose_name_plural': 'budžeti',
                'ordering': ['-godina', '-mjesec'],
                'constraints': [models.UniqueConstraint(fields=('korisnik', 'godina', 'mjesec'), name='jedan_budzet_po_mjesecu')],
            },
        ),
        migrations.AddConstraint(
            model_name='kategorija',
            constraint=models.UniqueConstraint(condition=models.Q(('vlasnik__isnull', True)), fields=('naziv',), name='jedinstvena_sustavska_kategorija'),
        ),
        migrations.AddConstraint(
            model_name='kategorija',
            constraint=models.UniqueConstraint(condition=models.Q(('vlasnik__isnull', False)), fields=('vlasnik', 'naziv'), name='jedinstvena_korisnicka_kategorija'),
        ),
        migrations.AddIndex(
            model_name='transakcija',
            index=models.Index(fields=['korisnik', '-datum'], name='core_transa_korisni_45af7c_idx'),
        ),
    ]
