# Generated by Django 6.0.7 on 2026-08-02 16:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pocetne_kategorije'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budzet',
            name='iznos',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='iznos'),
        ),
        migrations.AlterField(
            model_name='transakcija',
            name='iznos',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='iznos'),
        ),
    ]
