# Generated by Django 6.0.7 on 2026-08-12 08:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_budzet_iznos_alter_transakcija_iznos'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='profilna_slika',
            field=models.ImageField(blank=True, null=True, upload_to='profili/', verbose_name='profilna slika'),
        ),
        migrations.CreateModel(
            name='BudzetKategorije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.PositiveSmallIntegerField(verbose_name='godina')),
                ('mjesec', models.PositiveSmallIntegerField(verbose_name='mjesec')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='iznos')),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budzeti', to='core.kategorija', verbose_name='kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budzeti_kategorija', to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
            ],
            options={
                'verbose_name': 'budžet kategorije',
                'verbose_name_plural': 'budžeti kategorija',
                'ordering': ['-godina', '-mjesec', 'kategorija__naziv'],
                'constraints': [models.UniqueConstraint(fields=('korisnik', 'kategorija', 'godina', 'mjesec'), name='jedan_budzet_po_kategoriji_i_mjesecu')],
            },
        ),
    ]
