# Generated by Django 6.0.7 on 2026-08-18 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_korisnik_profilna_slika_budzetkategorije'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='obavijesti_garancije',
            field=models.BooleanField(default=True, verbose_name='obavijesti o garancijama'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='podsjetnik_garancije_dana',
            field=models.PositiveIntegerField(default=30, verbose_name='podsjetnik (dana prije isteka)'),
        ),
        migrations.CreateModel(
            name='Garancija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_proizvoda', models.CharField(max_length=255, verbose_name='naziv proizvoda')),
                ('datum_kupnje', models.DateField(verbose_name='datum kupnje')),
                ('datum_isteka', models.DateField(verbose_name='datum isteka')),
                ('serijski_broj', models.CharField(blank=True, default='', max_length=255, verbose_name='serijski broj')),
                ('napomena', models.TextField(blank=True, default='', verbose_name='napomena')),
                ('obavijesti', models.BooleanField(default=True, verbose_name='obavijesti')),
                ('datum_unosa', models.DateTimeField(auto_now_add=True, verbose_name='datum unosa')),
                ('datum_izmjene', models.DateTimeField(auto_now=True, verbose_name='datum izmjene')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garancije', to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
                ('racun', models.ForeignKey(blank=True, help_text='Neobavezno — garancija moze postojati i bez skeniranog racuna.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garancije', to='core.racun', verbose_name='račun')),
            ],
            options={
                'verbose_name': 'garancija',
                'verbose_name_plural': 'garancije',
                'ordering': ['datum_isteka'],
                'indexes': [models.Index(fields=['korisnik', 'datum_isteka'], name='core_garanc_korisni_e1ba47_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('datum_isteka__gte', models.F('datum_kupnje'))), name='istek_nakon_kupnje')],
            },
        ),
    ]
