# Generated by Django 6.0.7 on 2026-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_korisnik_obavijesti_garancije_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='garancija',
            name='istek_nakon_kupnje',
        ),
        migrations.AlterField(
            model_name='garancija',
            name='datum_isteka',
            field=models.DateField(blank=True, help_text='Prazno znaci dozivotna garancija.', null=True, verbose_name='datum isteka'),
        ),
        migrations.AddConstraint(
            model_name='garancija',
            constraint=models.CheckConstraint(condition=models.Q(('datum_isteka__isnull', True), ('datum_isteka__gte', models.F('datum_kupnje')), _connector='OR'), name='istek_nakon_kupnje'),
        ),
    ]
